jobs:
  publish-github-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: changelog
      name: Generate changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ secrets.GH_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      id: create_release
      name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        body: '### Things that changed in this release

          ${{ steps.changelog.outputs.changelog }}

          '
        draft: false
        prerelease: ${{ contains(github.event.inputs.releaseversion, '-') }}
        release_name: ${{ github.event.inputs.releaseversion }}
        tag_name: ${{ github.event.inputs.releaseversion }}
name: publish github release
on:
  repository_dispatch:
    types: trigger-ga___github-release.yml
