jobs:
  sync:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      uses: wearerequired/git-mirror-action@master
      with:
        destination-repo: git@gitee.com:log4j/pig.git
        source-repo: git@github.com:pig-mesh/pig.git
name: "\u540C\u6B65\u4EE3\u7801"
on:
  repository_dispatch:
    types: trigger-ga___mirror.yml
